sidebar:
  articles: Articles
  tags: Tags
  categories: Categories
  toggle_site: Toggle site
  toggle_article: Toggle article
  catalog: Catalog
  have_read: You've read

footer:
  driven: Driven
  theme: Theme

copy:
  success: Copy successfully
  error: Copy error
  noSupport: The browser does not support

page:
  articles: Articles
  tag: Tag
  category: Category

no_title: No title
